language: python
python:
    - "3.7"

env:
    -DJANGO_SETTINGS_MODULE='app.settings'

install:
    - pip install -r requirements.txt 


script: 
    coverage run app/manage.py test && flake8 && coverage report

after_success:
    - coveralls
